### ISSUE TITLE
AppKey申请问题

### ISSUE THREAD

**Issue by scaPEGoatno** [Qixingchen/MD-BiliBili#18]
请问你是怎样申请AppKey的。要有自己的网址吗?

**Comment by Qixingchen** [comment]
http://docs.bilibili.cn/wiki/分类:API
这里有申请地址。
不仅需要自己的网址，而且需要有可以控制根域的服务器空间。
另外这里的地址并不能最终申请到api key.在你能访问到B站的验证文件之后，请向B站客服发邮件继续申请。
2015年7月9日 16:11於 "jutangMai" notifications@github.com寫道：

**Comment by Qixingchen** [comment]
目前得知B站已停止API kEY发放.
~~Google一下就有了嘛~~
