### ISSUE TITLE
申请api key 地址是什么呢

### ISSUE THREAD

**Issue by tianshaokai** [Qixingchen/MD-BiliBili#21]
申请api key 地址是什么呢

**Comment by Qixingchen** [comment]
看下 #18

**Comment by tianshaokai** [comment]
有没有测试的apk key 呢，感觉申请好麻烦啊

**Comment by Qixingchen** [comment]
我们这没有，B站也没有发放测试的KEY。
你可以先用不需要API KEY的接口。
接口整理见
https://drive.google.com/folderview?id=0B5Izr6QMl6WhflNwY3MyZUlLMl8wdTNQdmROUVExNHpJVDV4Y3ZrcFc0c2VUa2lldEszbkE&usp=sharing
“需要API KEY”列没有打勾的接口都不需要API KEY。

2015-08-10 12:36 GMT+08:00 田绍凯 notifications@github.com:
