### ISSUE TITLE
Bilibili API Key在哪里申请

### ISSUE THREAD

**Issue by daojudada** [Qixingchen/MD-BiliBili#24]
只是一个学生，可以加入协作么，对B站比较感兴趣，想学习一下

**Comment by Qixingchen** [comment]
#18 中有申请 Api Key 方法的说明

**Comment by daojudada** [comment]
你好，万分感谢你的回复，我按你的提示打开了API申请的页面，并将验证文件放在我的根目录下，并且在浏览器能正常打开
http://www.nokogroup.org.cn/bilibili_5dccb97175cbb4989871a203089b0c6d.html
但是仍然无法通过验证
提示地址校验失败，请求对应地址数据失败，请确定此地址能正常访问
想请问是我哪里做错了么？当时你有碰到过类似的错误吗？想问下还有没有其他途径可以得到key，开发群有没有谁共享的呢？

**Comment by Qixingchen** [comment]
向B站客服发邮件继续申请。

2015-09-28 9:32 GMT+08:00 GuoJun notifications@github.com:

**Comment by daojudada** [comment]
你好=。=我跟B站客服人员邮件沟通后他们说已经关闭了B站API的申请，并且不再提供API KEY，想问还有什么办法可以参与这个项目吗T.T

**Comment by Qixingchen** [comment]
网上可以找到可用的key和password.
Google 前2页就找到了4个，全都有效。
