### ISSUE TITLE
一处代码错误

### ISSUE THREAD

**Issue by haogefeifei** [Qixingchen/MD-BiliBili#6]
/me/qixingchen/mdbilibili/AbsSwipeRecyclerViewFab.java 41行

![qq20150623-2](https://cloud.githubusercontent.com/assets/5234670/8286574/eed4521c-193c-11e5-8d51-ec930303774c.png)

另外，在Nexus5上，CardView都挨在一起了，没有README截图的一点点间隔。

![device-2015-06-23-000440](https://cloud.githubusercontent.com/assets/5234670/8286478/6657b1b8-193c-11e5-9fdd-356ff2cb77e8.png)

**Comment by Qixingchen** [comment]
界面还在等设计稿…

其实非常奇怪的是，在5.1的N5上…Toolbar是白色的…现在也没找到原因
2015年6月23日 00:13於 "好个飞飞" notifications@github.com寫道：

**Comment by haogefeifei** [comment]
哦？真按知乎上那个设计搞做？

**Comment by Harlber** [comment]
关于这处代码错误，，，我的处错，提交代码的时候提交的是单个文件，路径比较长，所以复制，保存下，，，我本地的倒是已经没有这个的了。我下次会注意的。

**Comment by Harlber** [comment]
<li>关于这处代码错误，，，我的错。提交代码的时候提交的是单个文件，路径比较长，所以复制，保存下。我下次会注意的。
<li>toolbar的白色的问题，我已注意到，私底下和相关人士交流过，可能是个toolbar的bug，更可能是我这边代码的问题，我去看下官方的文档。
<li>在Nexus5上，CardView都挨在一起，这个是没有做屏幕适配的缘故，我身边真机只有2个，原生ROM一个都没有，所以测试这边的话需要大家多多帮忙，以上的问题，我会尽快修复 by Farble

**Comment by haogefeifei** [comment]
干吧得。。

**Comment by Harlber** [comment]
@Qixingchen  @haogefeifei  toolbar白色问题修复
